version: '3.8'

services:
  # Dịch vụ Backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ecommerce_server
    # Không expose port ra ngoài host, Nginx sẽ truy cập qua mạng nội bộ của Docker
    expose:
      - '5000'
    env_file:
      - ./server/.env # Bạn sẽ cần tạo file này trên EC2
    restart: unless-stopped

  # Dịch vụ Frontend
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        # Client sẽ gửi request tới /api, và Nginx sẽ xử lý
        REACT_APP_API_URI: /api
        REACT_APP_LIMIT: 10
    container_name: ecommerce_client
    expose:
      - '80'
    restart: unless-stopped
    depends_on:
      - server

  # Dịch vụ Reverse Proxy
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: ecommerce_nginx
    ports:
      - "80:80" # Mở port 80 của host để nhận traffic từ bên ngoài
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
    restart: unless-stopped 